.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. revolvercoin_qt test_revolvercoin_qt
clean: FORCE
	$(MAKE) -C .. revolvercoin_qt_clean test_revolvercoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_revolvercoin_qt_check
revolvercoin-qt revolvercoin-qt.exe: FORCE
	 $(MAKE) -C .. revolvercoin_qt
