#ifndef REVOLVERCOIN_CHAINPARAMSSEEDS_H
#define REVOLVERCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the revolvercoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside a IPv6 address accordingly.
 */

static SeedSpec6 pnSeed6_main[] = {
    {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,0x8b,0x3b,0xac,0x0d}, 8777},
    {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,0xb2,0x3e,0x42,0x7c}, 8777}
};

static SeedSpec6 pnSeed6_test[] = {

};
#endif // REVOLVERCOIN_CHAINPARAMSSEEDS_H
